config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get '/charities', to: 'charities#index'
  # get '/charities/:id, to: 'charities#show'
  # get '/charties/new, to: 'charities#new'
  # post '/charities, to: 'charities#create'
  # get '/charities/:id/edit', to: 'charities#edit'
  # patch '/charities/:id, to: 'charities#update'
  # delete '/charties/:id, to: "charities#destroy"

  # resources :charities, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :charities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charity.rb
class Charity < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  def index
    @charities = Charity.all
  end

  def show
    @charity = Charity.find(params[:id])
  end

  def new
    @charity = Charity.new
  end

  def create
    charity = Charity.create(charity_params)
    redirect_to charity_path(charity)
  end

  def edit
    @charity = Charity.find(params[:id])
  end

  def update
    charity = Charity.find(params[:id])
    charity.update(charity_params)
    redirect_to charity_path(charity)
  end

  def destroy
    charity = Charity.find(params[:id])
    charity.destroy
    redirect_to charities_path
  end

  private

  def charity_params
    params.require(:charity).permit(:name, :category, :description, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charities/edit.html.erb
<h1>Edit a Charity</h1>

<%= form_with model: @charity do |f| %>
  <%= f.label :name, "Name: " %><br>
  <%= f.text_field :name %><br>

  <%= f.label :category, "Category: " %><br>
  <%= f.text_field :category %><br>

  <%= f.label :description, "Description: " %><br>
  <%= f.text_area :description, size: "20x5" %><br>
  
  <%= f.label :rating, "Rating: " %><br>
  <%= f.number_field :rating, in: 1..5 %><br><br>

  <%= f.submit "Edit Charity" %>
<% end %>

app/views/charities/index.html.erb
<h1>Charities</h1>

<p><%= link_to "Create New Charity", new_charity_path %></p>

<% @charities.each_with_index do |charity, idx| %>
  <p><%= idx + 1%>. <%= link_to(charity.name, charity_path(charity)) %> | <%= charity.category %></p>
<% end %>

app/views/charities/new.html.erb
<h1>Create a Charity</h1>

<%= form_with model: @charity do |f| %>
  <%= f.label :name, "Name: " %><br>
  <%= f.text_field :name %><br>

  <%= f.label :category, "Category: " %><br>
  <%= f.text_field :category %><br>

  <%= f.label :description, "Description: " %><br>
  <%= f.text_area :description, size: "20x5" %><br>
  
  <%= f.label :rating, "Rating: " %><br>
  <%= f.number_field :rating, in: 1..5 %><br><br>

  <%= f.submit "Create Charity" %>
<% end %>

app/views/charities/show.html.erb
<h2><%= @charity.name %></h2>
<p>Category: <%= @charity.category %></p>
<p>Description: <%= @charity.description %></p>
<p>Rating: <%= @charity.rating %></p>

<p><%= link_to "Edit", edit_charity_path(@charity) %></p>
<h3>Danger!</h3>
<%= button_to "Delete", "/charities/#{@charity.id}", method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Charities</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>